sudo: true
language: python
cache:
  directories:
  - $HOME/.pip-cache/
matrix:
  include:
  - python: '3.6'
    os: linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y wine
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
install:
- pip install --cache-dir $HOME/.pip-cache --upgrade pip codecov
- pip install --cache-dir $HOME/.pip-cache --upgrade git+https://github.com/drix00/pycasinotools.git
- pip install --cache-dir $HOME/.pip-cache --upgrade git+https://github.com/pymontecarlo/pymontecarlo.git
- pip install --cache-dir $HOME/.pip-cache --upgrade -e .[develop]
script:
- nosetests
after_success:
- codecov
notifications:
  email: false
